# Generated by Django 5.2.17 on 2026-09-19 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='description',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='partner',
            name='logo_url',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Логотип (URL или путь)'),
        ),
    ]
