# Generated by Django 5.2.17 on 2026-09-20 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_partner_description_partner_logo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutcompany',
            name='certificate',
            field=models.TextField(blank=True, null=True, verbose_name='Сертификат'),
        ),
    ]
