# Generated by Django 5.2.17 on 2026-09-20 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_aboutcompany_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='detailed_answer',
            field=models.TextField(blank=True, null=True, verbose_name='Развернутый ответ'),
        ),
        migrations.AlterField(
            model_name='term',
            name='answer',
            field=models.TextField(verbose_name='Краткий ответ'),
        ),
    ]
